server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    url: postgres://apglzybywnttai:f575e1d6859dd02314dd8c3a4917464659a210e2a0a672698f384fa25608aa1a@ec2-3-233-7-12.compute-1.amazonaws.com:5432/d8h7ffbplpu632
    username: apglzybywnttai
    password: f575e1d6859dd02314dd8c3a4917464659a210e2a0a672698f384fa25608aa1a
  jpa:
    show-sql: true
    data-platform: org.hibernate.dialect.PostgreDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
